//post
export const CREATE = "CREATE";
export const UPDATE = "UPDATE";
export const DELETE = "DELETE";
export const FETCH_ALL = "FETCH_ALL";
export const LIKE = "LIKE";

//login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

//
export const TOKEN_REQUEST = "TOKEN_REQUEST";
export const TOKEN_SUCCESS = "TOKEN_SUCCESS";
export const TOKEN_FAIL = "TOKEN_FAIL";

export const OPTION_REQUEST = "OPTION_REQUEST";
export const OPTION_SUCCESS = "OPTION_SUCCESS";
export const OPTION_FAIL = "OPTION_FAIL";

//OPTION buy
export const OPTION_BUY_REQUEST = "OPTION_BUY_REQUEST";
export const OPTION_BUY_SUCCESS = "OPTION_BUY_SUCCESS";
export const OPTION_BUY_FAIL = "OPTION_BUY_FAIL";
// option CUSTOMER
export const OPTION_BUY_CUSTOMER_REQUEST = "OPTION_BUY_CUSTOMER_REQUEST";
export const OPTION_BUY_CUSTOMER_SUCCESS = "OPTION_BUY_CUSTOMER_SUCCESS";
export const OPTION_BUY_CUSTOMER_FAIL = "OPTION_BUY_CUSTOMER_FAIL";
// option detail
export const OPTION_BUY_DETAIL_REQUEST = "OPTION_BUY_DETAIL_REQUEST";
export const OPTION_BUY_DETAIL_SUCCESS = "OPTION_BUY_DETAIL_SUCCESS";
export const OPTION_BUY_DETAIL_FAIL = "OPTION_BUY_DETAIL_FAIL";

//Buy
export const GET_LIST_BUY_REQUEST = "GET_LIST_BUY_REQUEST";
export const GET_LIST_BUY_SUCCESS = "GET_LIST_BUY_SUCCESS";
export const GET_LIST_BUY_FAIL = "GET_LIST_BUY_FAIL";

//Sale
export const GET_LIST_SALE_REQUEST = "GET_LIST_SALE_REQUEST";
export const GET_LIST_SALE_SUCCESS = "GET_LIST_SALE_SUCCESS";
export const GET_LIST_SALE_FAIL = "GET_LIST_SALE_FAIL";

//CUSTOMER

export const GET_LIST_CUSTOMER_REQUEST = "GET_LIST_CUSTOMER_REQUEST";
export const GET_LIST_CUSTOMER_SUCCESS = "GET_LIST_CUSTOMER_SUCCESS";
export const GET_LIST_CUSTOMER_FAIL = "GET_LIST_CUSTOMER_FAIL";

//DETAIL
export const GET_LIST_BUY_DETAIL_REQUEST = "GET_LIST_BUY_DETAIL_REQUEST";
export const GET_LIST_BUY_DETAIL_SUCCESS = "GET_LIST_BUY_DETAIL_SUCCESS";
export const GET_LIST_BUY_DETAIL_FAIL = "GET_LIST_BUY_DETAIL_FAIL";
